'use client';

import { useEffect, useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import { advanceBugProgress, BUGS, nextBugKey } from './bug-engine';
import type { Bug, BugKey } from './bug-engine';
import { generateAct1Map } from './act1-generation';
import type { EnemyKey, EventKey, MapNode, NodeKind } from './act1-generation';
import { createRng, nextRandom, normalizeSeed, pickSeeded, shuffleSeeded } from './seeded-rng';
import type { SeededRng } from './seeded-rng';

type CardKind = 'attack' | 'skill';
type Card = { id: number; key: string; name: string; code: string; art: string; cost: number; kind: CardKind; damage?: number; block?: number; heal?: number; draw?: number; energy?: number; selfDamage?: number };
type CardTemplate = Omit<Card, 'id'>;
type Screen = 'menu' | 'map' | 'battle' | 'reward' | 'event' | 'victory' | 'defeat';
type Enemy = { name: string; process: string; icon: string; hp: number; kind: NodeKind; feature: string };
type BugEvent = { triggeredName: string; reward: string; risk: string; mutatedTo: BugKey };
type Intent = { baseDamage: number; block: number; label: string };
type Battle = { enemyKey: EnemyKey; enemyHp: number; enemyShield: number; enemyStrength: number; playerHp: number; block: number; energy: number; turn: number; deck: Card[]; discard: Card[]; hand: Card[]; bug: BugKey; bugProgress: number; bugTriggers: number; bugTurnTriggers: number; energyDebt: number; attacksThisTurn: number; lastBugEvent: BugEvent | null; popupTurn: number; popupOpen: boolean; popupResolved: boolean; threat: number; intent: Intent; log: string[] };
type RunFlags = { daemonDraw: number; startingBlock: number; secretFragments: number; secretUnlocked: boolean; printerDebt: boolean };
type Run = { seed: string; rng: SeededRng; screen: Screen; hp: number; maxHp: number; cards: CardTemplate[]; cardSerial: number; map: MapNode[]; tier: number; completed: string[]; currentNode: string | null; battle: Battle | null; rewardChoices: CardTemplate[]; battlesWon: number; bugsTriggered: number; elitesDefeated: number; flags: RunFlags };

const CARD_LIBRARY: CardTemplate[] = [
  { key: 'strike', name: 'Compile Strike', code: 'compile()', art: '/card-art/compile-strike.webp', cost: 1, kind: 'attack', damage: 6 },
  { key: 'hotfix', name: 'Hotfix', code: 'patch --quick', art: '/card-art/hotfix.webp', cost: 1, kind: 'skill', block: 6 },
  { key: 'duck', name: 'Rubber Duck', code: 'explain(issue)', art: '/card-art/rubber-duck.webp', cost: 1, kind: 'skill', draw: 2 },
  { key: 'refactor', name: 'Refactor', code: 'clean(codebase)', art: '/card-art/refactor.webp', cost: 2, kind: 'attack', damage: 11 },
  { key: 'cache', name: 'Cache Shield', code: 'memoize(defense)', art: '/card-art/cache-shield.webp', cost: 2, kind: 'skill', block: 12 },
  { key: 'trace', name: 'Stack Trace', code: 'trace(stack)', art: '/card-art/stack-trace.webp', cost: 1, kind: 'attack', damage: 4, draw: 1 },
  { key: 'rollback', name: 'Rollback', code: 'git revert pain', art: '/card-art/rollback.webp', cost: 1, kind: 'skill', heal: 5 },
  { key: 'gc', name: 'Garbage Collect', code: 'gc.collect()', art: '/card-art/garbage-collect.webp', cost: 1, kind: 'skill', damage: 4, block: 4 },
  { key: 'pair', name: 'Pair Program', code: 'await teammate()', art: '/card-art/pair-program.webp', cost: 0, kind: 'skill', energy: 1 },
  { key: 'overclock', name: 'Overclock', code: 'cpu++', art: '/card-art/overclock.webp', cost: 2, kind: 'attack', damage: 15, selfDamage: 3 },
  { key: 'test', name: 'Unit Test', code: 'expect(safe)', art: '/card-art/unit-test.webp', cost: 1, kind: 'skill', block: 5, draw: 1 },
  { key: 'ship', name: 'Ship It', code: 'deploy --force', art: '/card-art/ship-it.webp', cost: 3, kind: 'attack', damage: 22 },
];
const byKey = (key: string) => CARD_LIBRARY.find((card) => card.key === key)!;
const STARTER_DECK = ['strike', 'strike', 'strike', 'strike', 'hotfix', 'hotfix', 'hotfix', 'hotfix', 'duck', 'pair'].map(byKey);
const ENEMIES: Record<EnemyKey, Enemy> = {
  folder: { name: 'Corrupted Folder', process: 'folder.exe', icon: '📁', hp: 35, kind: 'battle', feature: '会按 Seed 选择文件投掷或自我备份。' },
  cursor: { name: 'Broken Cursor', process: 'cursor.dll', icon: '↖', hp: 32, kind: 'battle', feature: '每回合第一张 Attack 少造成 3 伤害。' },
  trash: { name: 'Trash Beast', process: 'recycle.bin', icon: '🗑', hp: 44, kind: 'battle', feature: '攻击力随回合缓慢增长。' },
  frozen: { name: 'Frozen Window', process: 'window_404.exe', icon: '❐', hp: 40, kind: 'battle', feature: '每次你触发 Bug，它获得 3 Block。' },
  memoryHog: { name: 'Memory Hog', process: 'memory_hog.exe', icon: '🐗', hp: 62, kind: 'elite', feature: '你每触发 2 次 Bug，它永久获得 +2 攻击力。' },
  antivirus: { name: 'Antivirus', process: 'antivirus.sys', icon: '🛡', hp: 92, kind: 'boss', feature: 'Bug Trigger 提升 Threat；普通 Attack/Defend 不提升。' },
};

function roll(run: Run) { const result = nextRandom(run.rng); run.rng = result.rng; return result.value }
function pick<T>(run: Run, items: readonly T[]) { const result = pickSeeded(items, run.rng); run.rng = result.rng; return result.item }
function shuffle<T>(run: Run, items: T[]) { const result = shuffleSeeded(items, run.rng); run.rng = result.rng; return result.items }
function makeCards(run: Run, templates: CardTemplate[]) { return templates.map((card) => ({ ...card, id: run.cardSerial++ })) }
function drawCards(run: Run, battle: Battle, count: number) { for (let i = 0; i < count; i += 1) { if (!battle.deck.length) { if (!battle.discard.length) return; battle.deck = shuffle(run, battle.discard); battle.discard = []; battle.log.unshift('↻ discard.log 已按 Seed 重新载入 deck.memory') } const card = battle.deck.shift(); if (card) battle.hand.push(card) } }
function randomSeed() { const values = new Uint32Array(2); crypto.getRandomValues(values); return `${values[0].toString(36)}-${values[1].toString(36)}`.toUpperCase() }
function createRun(seed: string): Run { const normalized = normalizeSeed(seed); const generated = generateAct1Map(createRng(normalized)); return { seed: normalized, rng: generated.rng, screen: 'map', hp: 48, maxHp: 48, cards: [...STARTER_DECK], cardSerial: 1, map: generated.nodes, tier: 0, completed: [], currentNode: null, battle: null, rewardChoices: [], battlesWon: 0, bugsTriggered: 0, elitesDefeated: 0, flags: { daemonDraw: 0, startingBlock: 0, secretFragments: 0, secretUnlocked: false, printerDebt: false } } }
function menuRun() { const run = createRun('DEBUG-0001'); run.screen = 'menu' as const; return run }

function nextIntent(run: Run, enemyKey: EnemyKey, turn: number): Intent { const value = roll(run); if (enemyKey === 'folder') return value < .35 ? { baseDamage: 5, block: 8, label: '备份 + 攻击' } : { baseDamage: 7, block: 0, label: '文件投掷' }; if (enemyKey === 'cursor') return value < .45 ? { baseDamage: 10, block: 0, label: '乱点双击' } : { baseDamage: 6, block: 0, label: '指针突刺' }; if (enemyKey === 'trash') return { baseDamage: 6 + Math.floor(turn / 2) * 2 + (value < .22 ? 3 : 0), block: 0, label: value < .22 ? '清空回收站' : '垃圾堆积' }; if (enemyKey === 'frozen') return value < .42 ? { baseDamage: 5, block: 7, label: '冻结 + 攻击' } : { baseDamage: 9, block: 0, label: '未响应' }; if (enemyKey === 'memoryHog') return value < .3 ? { baseDamage: 14, block: 0, label: '内存峰值' } : { baseDamage: 9, block: 0, label: '内存挪用' }; return value < .3 ? { baseDamage: 13, block: 0, label: 'FULL SCAN' } : { baseDamage: 8, block: 0, label: 'QUICK SCAN' } }
function shownIntent(battle: Battle) { return { ...battle.intent, damage: battle.intent.baseDamage + battle.enemyStrength + (battle.enemyKey === 'antivirus' ? battle.threat * 2 : 0) } }
function createBattle(run: Run, enemyKey: EnemyKey): Battle { const cards = shuffle(run, makeCards(run, run.cards)); const bug = pick(run, Object.keys(BUGS) as BugKey[]); const popupTurn = 2 + Math.floor(roll(run) * 3); const enemyStrength = (run.flags.daemonDraw ? 1 : 0) + (run.flags.printerDebt ? 1 : 0); const battle: Battle = { enemyKey, enemyHp: ENEMIES[enemyKey].hp, enemyShield: 0, enemyStrength, playerHp: run.hp, block: run.flags.startingBlock, energy: 3, turn: 1, deck: cards, discard: [], hand: [], bug, bugProgress: 0, bugTriggers: 0, bugTurnTriggers: 0, energyDebt: 0, attacksThisTurn: 0, lastBugEvent: null, popupTurn, popupOpen: false, popupResolved: false, threat: 0, intent: { baseDamage: 0, block: 0, label: '' }, log: [`ACTIVE BUG: ${BUGS[bug].name}`, `HOST FOUND: ${ENEMIES[enemyKey].name}`, `RUN SEED: ${run.seed}`] }; drawCards(run, battle, 5 + run.flags.daemonDraw); battle.intent = nextIntent(run, enemyKey, 1); if (enemyStrength) battle.log.unshift(`⚠ 延迟进程生效：敌人 +${enemyStrength} 攻击力`); run.flags.daemonDraw = 0; run.flags.startingBlock = 0; run.flags.printerDebt = false; return battle }
function damageEnemy(battle: Battle, amount: number) { const absorbed = Math.min(battle.enemyShield, amount); battle.enemyShield -= absorbed; battle.enemyHp = Math.max(0, battle.enemyHp - amount + absorbed) }
function recordBug(run: Run, battle: Battle, triggeredBug: BugKey, reward: string, risk: string) { battle.bugTriggers += 1; battle.bugTurnTriggers += 1; battle.log.unshift(`🐛 ${BUGS[triggeredBug].name} #${battle.bugTriggers} // ${reward} // ${risk}`); if (battle.enemyKey === 'frozen') { battle.enemyShield += 3; battle.log.unshift('! Frozen Window 封存 Bug 活动：+3 Block') } if (battle.enemyKey === 'memoryHog' && battle.bugTriggers % 2 === 0) { battle.enemyStrength += 2; battle.log.unshift('! Memory Hog 吞掉调试数据：+2 攻击力') } if (battle.enemyKey === 'antivirus') { battle.threat = Math.min(6, battle.threat + 1); battle.log.unshift(`⚠ ANTIVIRUS THREAT LEVEL ${battle.threat}/6`) } const mutatedTo = nextBugKey(triggeredBug, () => roll(run)); battle.bug = mutatedTo; battle.bugProgress = 0; battle.lastBugEvent = { triggeredName: BUGS[triggeredBug].name, reward, risk, mutatedTo }; battle.log.unshift(`↻ BUG MUTATED // ${BUGS[triggeredBug].name} → ${BUGS[mutatedTo].name}`) }
function rewardOptions(run: Run) { return shuffle(run, CARD_LIBRARY.filter((card) => !['strike', 'hotfix'].includes(card.key))).slice(0, 3) }

export default function Page() {
  const [run, setRun] = useState<Run>(menuRun); const battle = run.battle;
  const canPlay = useMemo(() => Boolean(battle?.hand.some((card) => card.cost <= battle.energy)), [battle?.hand, battle?.energy]);
  useEffect(() => {
    if (run.screen !== 'map') return;
    const frame = requestAnimationFrame(() => {
      document.querySelector<HTMLElement>(`.map-tier[data-tier="${run.tier}"]`)?.scrollIntoView({ behavior: 'smooth', block: 'nearest', inline: 'center' });
    });
    return () => cancelAnimationFrame(frame);
  }, [run.screen, run.tier]);
  const enterNode = (node: MapNode) => setRun((previous) => { if (node.tier !== previous.tier || (node.kind === 'secret' && !previous.flags.secretUnlocked)) return previous; const next = structuredClone(previous) as Run; next.currentNode = node.id; if (node.event) next.screen = 'event'; else if (node.enemy) { next.screen = 'battle'; next.battle = createBattle(next, node.enemy) } return next });
  const playCard = (cardId: number) => setRun((previous) => {
    if (previous.screen !== 'battle' || !previous.battle || previous.battle.popupOpen) return previous;
    const next = structuredClone(previous) as Run; const active = next.battle!; const played = active.hand.find((card) => card.id === cardId); if (!played || played.cost > active.energy) return previous;
    active.hand = active.hand.filter((card) => card.id !== cardId); active.energy -= played.cost; const energyAfterSpend = active.energy;
    let cardDamage = played.damage ?? 0; if (active.enemyKey === 'cursor' && played.kind === 'attack' && active.attacksThisTurn === 0) { cardDamage = Math.max(0, cardDamage - 3); active.log.unshift('! Broken Cursor 让第一次 Attack 偏移：伤害 -3') }
    if (cardDamage) damageEnemy(active, cardDamage); if (played.block) active.block += played.block; if (played.heal) active.playerHp = Math.min(next.maxHp, active.playerHp + played.heal); if (played.selfDamage) active.playerHp = Math.max(0, active.playerHp - played.selfDamage); if (played.energy) active.energy += played.energy; if (played.draw) drawCards(next, active, played.draw); active.discard.push(played); if (played.kind === 'attack') active.attacksThisTurn += 1; active.log.unshift(`> ${played.name} // ${describeCard(played)}`);
    const triggeredBug = active.bug; const result = advanceBugProgress(triggeredBug, active.bugProgress, { cardKind: played.kind, cost: played.cost, blockGained: played.block ?? 0, cardsDrawn: played.draw ?? 0, energyAfterSpend }); active.bugProgress = result.progress;
    if (result.triggered) { if (triggeredBug === 'overflow') { drawCards(next, active, 2); active.energy += 1; active.enemyStrength += 1; recordBug(next, active, triggeredBug, '抽 2，+1 Energy', '敌人 +1 攻击力') } else if (triggeredBug === 'memory') { drawCards(next, active, 2); active.playerHp = Math.max(0, active.playerHp - 2); recordBug(next, active, triggeredBug, '额外抽 2', '失去 2 HP') } else if (triggeredBug === 'hotPath') { damageEnemy(active, 6); active.playerHp = Math.max(0, active.playerHp - 2); recordBug(next, active, triggeredBug, '额外 6 伤害', '失去 2 HP') } else if (triggeredBug === 'firewall') { active.block += 8; active.energyDebt += 1; recordBug(next, active, triggeredBug, '+8 Block', '下回合 -1 Energy') } else { active.energy += 2; active.playerHp = Math.max(0, active.playerHp - 3); recordBug(next, active, triggeredBug, '+2 Energy', '失去 3 HP') } }
    if (active.playerHp <= 0) { next.hp = 0; next.battle = null; next.screen = 'defeat' } else if (active.enemyHp <= 0) { next.hp = active.playerHp; next.bugsTriggered += active.bugTriggers; next.battlesWon += 1; next.completed.push(next.currentNode!); if (ENEMIES[active.enemyKey].kind === 'elite') next.elitesDefeated += 1; next.battle = null; if (active.enemyKey === 'antivirus') next.screen = 'victory'; else { next.screen = 'reward'; next.rewardChoices = rewardOptions(next) } } return next;
  });
  const endTurn = () => setRun((previous) => { if (previous.screen !== 'battle' || !previous.battle || previous.battle.popupOpen) return previous; const next = structuredClone(previous) as Run; const active = next.battle!; const intent = shownIntent(active); const damageTaken = Math.max(0, intent.damage - active.block); active.playerHp = Math.max(0, active.playerHp - damageTaken); active.log.unshift(`! ${ENEMIES[active.enemyKey].name} // ${intent.label} ${intent.damage} // HP -${damageTaken}`); if (active.playerHp <= 0) { next.hp = 0; next.battle = null; next.screen = 'defeat'; return next } active.enemyShield = intent.block; active.discard.push(...active.hand); active.hand = []; active.block = 0; active.turn += 1; active.energy = Math.max(0, 3 - active.energyDebt); if (active.energyDebt) active.log.unshift(`⚠ ENERGY DEBT // 本回合 -${active.energyDebt} Energy`); active.energyDebt = 0; active.attacksThisTurn = 0; active.bugProgress = 0; active.bugTurnTriggers = 0; active.lastBugEvent = null; drawCards(next, active, 5); active.intent = nextIntent(next, active.enemyKey, active.turn); if (!active.popupResolved && active.turn === active.popupTurn) active.popupOpen = true; active.log.unshift(`— TURN ${active.turn} // Energy restored`); return next });
  const resolvePopup = (choice: 'allow' | 'deny') => setRun((previous) => { if (!previous.battle?.popupOpen) return previous; const next = structuredClone(previous) as Run; const active = next.battle!; if (choice === 'allow') { drawCards(next, active, 2); active.energy += 1; active.playerHp = Math.max(0, active.playerHp - 4); active.log.unshift('▣ POP-UP // ALLOW：抽 2，+1 Energy，失去 4 HP') } else { active.block += 9; active.energyDebt += 1; active.log.unshift('▣ POP-UP // NOT NOW：+9 Block，下回合 -1 Energy') } active.popupOpen = false; active.popupResolved = true; if (active.playerHp <= 0) { next.hp = 0; next.battle = null; next.screen = 'defeat' } return next });
  const finishReward = (card?: CardTemplate) => setRun((previous) => ({ ...previous, cards: card ? [...previous.cards, card] : previous.cards, tier: previous.tier + 1, screen: 'map', battle: null, currentNode: null, rewardChoices: [] }));
  const resolveEvent = (choice: 'left' | 'right') => setRun((previous) => { const next = structuredClone(previous) as Run; const node = next.map.find((item) => item.id === next.currentNode); if (!node?.event) return previous; if (node.event === 'update') { if (choice === 'left') next.hp = Math.min(next.maxHp, next.hp + 14); else next.cards.push(byKey('test')) } if (node.event === 'unknownExe') { if (choice === 'left') { next.hp = Math.max(1, next.hp - 5); next.cards.push(pick(next, CARD_LIBRARY.filter((card) => !['strike', 'hotfix'].includes(card.key)))); next.flags.daemonDraw = 1; if (node.anomaly) next.flags.secretFragments += 1 } else { next.flags.startingBlock += 9; next.maxHp += 2; next.hp += 2 } } if (node.event === 'recursiveFolder') { if (choice === 'left') { next.hp = Math.max(1, next.hp - 3); next.flags.secretFragments += 1; next.cards.push(byKey('trace')) } else next.hp = Math.min(next.maxHp, next.hp + 7) } if (node.event === 'printerGhost') { if (choice === 'left') { next.hp = Math.min(next.maxHp, next.hp + 4 + Math.floor(roll(next) * 6)); next.flags.printerDebt = true } else next.cards.push(byKey('rollback')) } if (node.event === 'secretRoot') { if (choice === 'left') { next.cards.push(byKey('ship')); next.maxHp += 4; next.hp += 4 } else { next.cards.push(byKey('cache')); next.hp = Math.min(next.maxHp, next.hp + 12) } } const secretNode = next.map.find((item) => item.kind === 'secret'); if (secretNode && !secretNode.hidden && next.flags.secretFragments > 0) next.flags.secretUnlocked = true; next.completed.push(next.currentNode!); next.tier += 1; next.screen = 'map'; next.currentNode = null; return next });
  const bugInfo = battle ? BUGS[battle.bug] : null; const enemy = battle ? ENEMIES[battle.enemyKey] : null; const intent = battle ? shownIntent(battle) : null; const displayedHp = battle ? battle.playerHp : run.hp;
  return <main><header className="topbar"><div className="brand"><span className="brand-mark">B_</span><div><h1>BUGBOUND</h1><p>desktop run // deterministic build</p></div></div>{run.screen !== 'menu' ? <><div className="seed-chip"><span>RUN SEED</span><strong>{run.seed}</strong><small>RNG #{run.rng.calls}</small></div><div className="run-health"><span>SYSTEM HEALTH</span><strong>{displayedHp}/{run.maxHp}</strong></div></> : null}<button className="ghost-button" onClick={() => setRun(menuRun())}>⌂ RUN MENU</button></header>{run.screen === 'menu' ? <MainMenu onStart={(seed) => setRun(createRun(seed))} /> : null}{run.screen === 'map' ? <MapScreen run={run} onEnter={enterNode} /> : null}{run.screen === 'battle' && battle && bugInfo && enemy && intent ? <BattleScreen run={run} battle={battle} bug={bugInfo} enemy={enemy} intent={intent} canPlay={canPlay} onPlay={playCard} onEndTurn={endTurn} onPopup={resolvePopup} /> : null}{run.screen === 'reward' ? <RewardScreen choices={run.rewardChoices} onChoose={finishReward} /> : null}{run.screen === 'event' ? <EventScreen run={run} onChoose={resolveEvent} /> : null}{run.screen === 'victory' || run.screen === 'defeat' ? <RunResult run={run} onReset={() => setRun(menuRun())} /> : null}</main>;
}

function MainMenu({ onStart }: { onStart: (seed: string) => void }) { const [seed, setSeed] = useState('DEBUG-0001'); return <section className="center-screen menu-screen"><div className="main-menu"><span>BOOT SEQUENCE READY</span><h2>Every bug has an address.</h2><p>同一个 Seed，加上完全相同的路线、出牌和选择，会得到完全相同的 Run。</p><button className="primary-run" onClick={() => onStart(randomSeed())}><strong>NEW RUN</strong><small>生成新的 Seed</small></button><div className="seed-entry"><label htmlFor="seed">ENTER SEED / SEEDED RUN</label><div><input id="seed" value={seed} maxLength={24} onChange={(event) => setSeed(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') onStart(seed) }} /><button onClick={() => onStart(seed)}>BOOT</button></div></div><code>SAME SEED + SAME INPUTS = SAME RUN</code></div></section> }

function MapScreen({ run, onEnter }: { run: Run; onEnter: (node: MapNode) => void }) { const tiers = Array.from({ length: 11 }, (_, index) => index); return <section className="map-shell"><div className="explorer-bar"><span className="window-controls"><i /><i /><i /></span><strong>File Explorer</strong><code>C:\Desktop\Act_1\seed_{run.seed}</code></div><div className="map-intro"><div><span>ACT 1 / DESKTOP</span><h2>Choose a system path.</h2><p>未来节点全部可见。安全路线保资源，风险路线可能让坏事变成 Build 的一部分。</p></div><div className="developer-id"><span>🧑‍💻</span><div><small>RUN SEED</small><strong>{run.seed}</strong><p>RNG CALLS {run.rng.calls} · 可复制分享与 Debug</p></div></div></div><div className="path-map seeded-map">{tiers.map((tier) => <div className="map-tier" data-tier={tier} key={tier}><span className="tier-label">{tier === 10 ? 'ANTIVIRUS' : `PATH ${String(tier + 1).padStart(2, '0')}`}</span><div className="tier-nodes">{run.map.filter((node) => node.tier === tier && (node.kind !== 'secret' || run.flags.secretUnlocked)).map((node) => { const unlocked = run.tier === tier; const completed = run.completed.includes(node.id); const passed = run.tier > tier && !completed; return <button key={node.id} className={`map-node ${node.kind} ${node.anomaly ? 'anomaly' : ''} ${unlocked ? 'unlocked' : ''} ${completed ? 'completed' : ''}`} disabled={!unlocked} onClick={() => onEnter(node)}><span className="node-icon">{node.kind === 'battle' ? '⚔' : node.kind === 'elite' ? '☠' : node.kind === 'boss' ? '🛡' : node.kind === 'secret' ? '⌘' : node.anomaly ? '⚠' : '▣'}</span><span><small>{node.anomaly ? 'ROUTE ANOMALY' : node.kind.toUpperCase()}</small><strong>{node.label}</strong><code>{node.path}</code></span><b>{completed ? '✓' : passed ? '—' : unlocked ? 'OPEN' : '🔒'}</b></button> })}</div></div>)}</div><footer className="run-footer"><span>SEED {run.seed}</span><span>DECK {run.cards.length}</span><span>BATTLES {run.battlesWon}</span><span>BUG TRIGGERS {run.bugsTriggered}</span>{run.flags.daemonDraw ? <span className="warning">BACKGROUND PROCESS PENDING</span> : null}</footer></section> }

function BattleScreen({ run, battle, bug, enemy, intent, canPlay, onPlay, onEndTurn, onPopup }: { run: Run; battle: Battle; bug: Bug; enemy: Enemy; intent: ReturnType<typeof shownIntent>; canPlay: boolean; onPlay: (id: number) => void; onEndTurn: () => void; onPopup: (choice: 'allow' | 'deny') => void }) { return <><section className="mission-line"><span>{enemy.kind === 'boss' ? 'SECURITY ALERT' : 'ACTIVE PROCESS'}</span><p>{enemy.feature}</p><span className="turn">TURN {String(battle.turn).padStart(2, '0')}</span></section><div className="workspace"><section className="battle-panel">{battle.enemyKey === 'antivirus' ? <ThreatMeter threat={battle.threat} /> : null}<div className="combatants"><div className="actor player"><div className="avatar developer-avatar">🧑‍💻</div><div className="actor-copy"><div className="eyebrow">PLAYER_PROCESS</div><h2>Developer</h2><StatBar label="HP" value={battle.playerHp} max={run.maxHp} tone="green" /><div className="mini-stats"><span>🛡 {battle.block} BLOCK</span><span>⚡ {battle.energy}/3 ENERGY</span></div>{battle.energyDebt ? <div className="energy-debt">NEXT TURN −{battle.energyDebt} ENERGY</div> : null}</div></div><div className="versus">VS</div><div className="actor enemy"><div className="actor-copy"><div className="eyebrow danger">{enemy.process}</div><h2>{enemy.name}</h2><StatBar label="HP" value={battle.enemyHp} max={enemy.hp} tone="red" />{battle.enemyShield ? <div className="enemy-shield">🛡 {battle.enemyShield} BLOCK</div> : null}<div className="intent"><span>{intent.label}</span><strong>⚔ {intent.damage} DAMAGE{intent.block ? ` + ${intent.block} BLOCK` : ''}</strong></div>{battle.enemyStrength ? <div className="enemy-mods"><span>+{battle.enemyStrength} STR</span></div> : null}</div><div className={`avatar enemy-avatar ${battle.enemyKey}`}>{enemy.icon}</div></div></div><div className="hand-zone"><div className="zone-heading"><div><span>HAND</span><small>{battle.hand.length} cards · deck {battle.deck.length} · discard {battle.discard.length}</small></div><button className="end-button" onClick={onEndTurn}>END TURN <b>↵</b></button></div><div className="cards">{battle.hand.map((card, index) => <CardButton key={card.id} card={card} index={index} disabled={card.cost > battle.energy} onPlay={onPlay} />)}{!battle.hand.length ? <div className="empty-hand">HAND EMPTY</div> : null}</div>{!canPlay ? <p className="hint">没有可出的牌了——结束回合，让系统继续运行。</p> : null}</div></section><aside className="sidebar"><BugMonitor bug={bug} battle={battle} /><section className="terminal window-panel"><WindowTitle title={`Runtime.log // ${run.seed}`} /><div className="log-lines">{battle.log.slice(0, 10).map((line, index) => <p key={`${line}-${index}`} className={line.includes('BUG') || line.includes('🐛') || line.includes('THREAT') ? 'alert' : ''}>{line}</p>)}</div></section></aside></div>{battle.popupOpen ? <PopupDialog onChoose={onPopup} /> : null}</> }

function CardButton({ card, index, disabled, onPlay }: { card: Card; index: number; disabled: boolean; onPlay: (id: number) => void }) { return <button className={`card drawn-card ${card.kind}`} style={{ '--draw-order': index } as CSSProperties} disabled={disabled} onClick={() => onPlay(card.id)}><span className="cost">{card.cost}</span><span className="kind">{card.kind.toUpperCase()}</span><span className="card-art"><img src={card.art} alt="" /></span><strong>{card.name}</strong><code>{card.code}</code><span className="effect">{describeCard(card)}</span><span className="run">{disabled ? 'INSUFFICIENT ENERGY' : 'CLICK TO RUN'}</span></button> }
function BugMonitor({ bug, battle }: { bug: Bug; battle: Battle }) { const event = battle.lastBugEvent; return <section className={`bug-monitor window-panel ${event ? 'triggered' : ''}`}><WindowTitle title="BugMonitor.exe" live /><div className="bug-head"><div className="bug-symbol">{bug.icon}</div><div><span>{bug.code} / {bug.category}</span><h3>{bug.name}</h3></div></div><div className="bug-rule trigger"><span>TRIGGER</span><p>{bug.trigger}</p></div>{bug.target ? <div className="bug-progress"><span>{bug.progressLabel}</span><div><i style={{ width: `${Math.min(100, (battle.bugProgress / bug.target) * 100)}%` }} /></div><strong>{battle.bugProgress}/{bug.target}</strong></div> : null}<div className="bug-rule reward"><span>REWARD</span><p>{bug.reward}</p></div><div className="bug-rule risk"><span>RISK</span><p>{bug.risk}</p></div><div className="trigger-count"><div><span>THIS TURN</span><strong>{battle.bugTurnTriggers}</strong></div><div><span>THIS BATTLE</span><strong>{battle.bugTriggers}</strong></div></div>{event ? <div key={battle.bugTriggers} className="bug-feedback"><strong>BUG MUTATED</strong><span>{event.triggeredName} → {BUGS[event.mutatedTo].name}</span><small>TRIGGERED #{battle.bugTriggers} // + {event.reward} / − {event.risk}</small></div> : null}<p className="bug-note">每次触发立即换成 Seed 决定的新目标；Bug 奖励本身不会触发下一个 Bug。</p></section> }
function WindowTitle({ title, live = false }: { title: string; live?: boolean }) { return <div className="window-title"><span>{title}</span><span className="window-actions"><i className={live ? 'live' : ''} />─ □ ×</span></div> }
function ThreatMeter({ threat }: { threat: number }) { return <div className={`threat-meter threat-${threat}`}><span>🛡 ANTIVIRUS THREAT LEVEL</span><div>{Array.from({ length: 6 }, (_, index) => <i key={index} className={index < threat ? 'filled' : ''} />)}</div><strong>{threat}/6</strong><small>只有主动 Bug Trigger 使扫描伤害 +2</small></div> }
function PopupDialog({ onChoose }: { onChoose: (choice: 'allow' | 'deny') => void }) { return <div className="overlay popup-overlay" role="dialog" aria-modal="true"><div className="os-dialog"><WindowTitle title="Unknown process permission" /><div className="dialog-body"><div className="dialog-icon">!</div><div><h2>Allow background optimization?</h2><p><code>helper_undefined.exe</code> 想优化本回合资源。两个选择都有代价。</p></div></div><div className="dialog-choices"><button onClick={() => onChoose('allow')}><strong>ALLOW</strong><span>抽 2，+1 Energy</span><small>Risk：失去 4 HP</small></button><button onClick={() => onChoose('deny')}><strong>NOT NOW</strong><span>+9 Block</span><small>Risk：下回合 -1 Energy</small></button></div></div></div> }
function RewardScreen({ choices, onChoose }: { choices: CardTemplate[]; onChoose: (card?: CardTemplate) => void }) { return <section className="center-screen"><div className="reward-window"><WindowTitle title="Package Manager / Seeded reward" /><div className="screen-copy"><span>PROCESS TERMINATED</span><h2>Install one new command.</h2><p>三个候选与顺序都由当前 Run Seed 决定。</p></div><div className="reward-cards">{choices.map((card) => <button key={card.key} className={`card ${card.kind}`} onClick={() => onChoose(card)}><span className="cost">{card.cost}</span><span className="kind">{card.kind.toUpperCase()}</span><span className="card-art"><img src={card.art} alt="" /></span><strong>{card.name}</strong><code>{card.code}</code><span className="effect">{describeCard(card)}</span><span className="run">INSTALL</span></button>)}</div><button className="skip-button" onClick={() => onChoose()}>跳过安装 →</button></div></section> }

const EVENT_COPY: Record<EventKey, { title: string; eyebrow: string; body: string; left: [string, string, string]; right: [string, string, string] }> = {
  update: { title: 'One maintenance window is available.', eyebrow: 'OPTIONAL UPDATE FOUND', body: '没有免费升级：修复现有系统，或为后续战斗安装新工具。', left: ['SYSTEM RESTORE', '恢复 14 HP', '稳定且可预测'], right: ['FEATURE UPDATE', '获得 Unit Test', '5 Block · 抽 1'] },
  unknownExe: { title: 'Unknown.exe asks to be useful.', eyebrow: 'UNSIGNED PROCESS', body: '它保证“只运行一次”。窗口背后似乎还有另一个窗口。', left: ['RUN ANYWAY', '失去 5 HP · 获得随机牌', '下场多抽 1；敌人 +1 STR'], right: ['SANDBOX IT', '下场 +9 Block · Max HP +2', '它仍然知道你的用户名'] },
  recursiveFolder: { title: 'A folder contains the Desktop.', eyebrow: 'PATH RESOLUTION FAILED', body: '里面又有一个你，正在犹豫要不要打开这个文件夹。', left: ['FOLLOW STACK', '失去 3 HP · 获得 Stack Trace', '留下一个 secret fragment'], right: ['CLOSE WINDOW', '恢复 7 HP', '假装什么都没看见'] },
  printerGhost: { title: 'The offline printer printed your log.', eyebrow: 'DEVICE NOT CONNECTED', body: '最后一行写着下一场战斗的结果，但墨水晕开了。', left: ['READ IT', '随机恢复 4–9 HP', '下场敌人 +1 STR'], right: ['SHRED IT', '获得 Rollback', '纸屑拼出了你的 Seed'] },
  secretRoot: { title: 'You were already logged in.', eyebrow: 'HIDDEN USER PROFILE', body: '头像是你。创建日期比这台电脑更早。', left: ['OPEN PROFILE', '获得 Ship It · Max HP +4', 'Antivirus 已记录访问'], right: ['COPY CACHE', '获得 Cache Shield · 恢复 12 HP', '不要回头看进程列表'] },
};
function EventScreen({ run, onChoose }: { run: Run; onChoose: (choice: 'left' | 'right') => void }) { const node = run.map.find((item) => item.id === run.currentNode); const copy = EVENT_COPY[node?.event ?? 'update']; return <section className="center-screen"><div className={`event-window ${node?.anomaly ? 'event-anomaly' : ''}`}><WindowTitle title={node?.anomaly ? `route_corruption.exe // ${run.seed}` : `${node?.label ?? 'Event'} // ${run.seed}`} /><div className="update-visual"><span>{node?.anomaly ? '?' : '↻'}</span><i /></div><div className="screen-copy"><span>{copy.eyebrow}</span><h2>{copy.title}</h2><p>{copy.body}</p></div><div className="event-options"><button onClick={() => onChoose('left')}><span>{copy.left[0]}</span><strong>{copy.left[1]}</strong><small>{copy.left[2]}</small></button><button onClick={() => onChoose('right')}><span>{copy.right[0]}</span><strong>{copy.right[1]}</strong><small>{copy.right[2]}</small></button></div></div></section> }
function RunResult({ run, onReset }: { run: Run; onReset: () => void }) { const won = run.screen === 'victory'; return <section className="center-screen"><div className={`result ${won ? 'won' : 'lost'}`}><span>{won ? 'ACT 1 COMPLETE' : 'FATAL ERROR'}</span><div className="result-icon">{won ? '💻' : '⊘'}</div><h2>{won ? 'Antivirus 已撤销隔离。' : '进程已崩溃。'}</h2><p>{won ? '它说这是一次误报。但你的隐藏用户目录仍在运行。' : '用同一个 Seed 与操作，可以准确重现这次崩溃。'}</p><div className="result-seed"><small>RUN SEED</small><strong>{run.seed}</strong><span>RNG CALLS {run.rng.calls}</span></div><div className="run-summary"><span><small>BATTLES</small>{run.battlesWon}</span><span><small>BUG TRIGGERS</small>{run.bugsTriggered}</span><span><small>FINAL DECK</small>{run.cards.length}</span></div><button onClick={onReset}>RETURN TO RUN MENU ↻</button></div></section> }
function StatBar({ label, value, max, tone }: { label: string; value: number; max: number; tone: string }) { return <div className="stat-wrap"><div className="stat-label"><span>{label}</span><strong>{value}/{max}</strong></div><div className={`stat-bar ${tone}`}><i style={{ width: `${Math.max(0, value / max) * 100}%` }} /></div></div> }
function describeCard(card: CardTemplate) { const parts = []; if (card.damage) parts.push(`造成 ${card.damage} 伤害`); if (card.block) parts.push(`获得 ${card.block} Block`); if (card.heal) parts.push(`修复 ${card.heal} HP`); if (card.draw) parts.push(`抽 ${card.draw} 张牌`); if (card.energy) parts.push(`获得 ${card.energy} Energy`); if (card.selfDamage) parts.push(`失去 ${card.selfDamage} HP`); return parts.join(' · ') }
