'use client';

import { useMemo, useState } from 'react';
import type { CSSProperties } from 'react';
import { advanceBugProgress, BUGS, nextBugKey } from './bug-engine';
import type { Bug, BugKey } from './bug-engine';

type CardKind = 'attack' | 'skill';
type Card = { id: number; key: string; name: string; code: string; art: string; cost: number; kind: CardKind; damage?: number; block?: number; heal?: number; draw?: number; energy?: number; selfDamage?: number };
type CardTemplate = Omit<Card, 'id'>;
type EnemyKey = 'folder' | 'cursor' | 'trash' | 'frozen' | 'memoryHog' | 'antivirus';
type NodeKind = 'battle' | 'elite' | 'event' | 'boss';
type Screen = 'map' | 'battle' | 'reward' | 'event' | 'victory' | 'defeat';
type Enemy = { name: string; process: string; icon: string; hp: number; kind: NodeKind; feature: string };
type MapNode = { id: string; tier: number; kind: NodeKind; enemy?: EnemyKey; label: string; path: string };
type BugEvent = { triggeredName: string; reward: string; risk: string; mutatedTo: BugKey };
type Battle = { enemyKey: EnemyKey; enemyHp: number; enemyShield: number; enemyStrength: number; playerHp: number; block: number; energy: number; turn: number; deck: Card[]; discard: Card[]; hand: Card[]; bug: BugKey; bugProgress: number; bugTriggers: number; bugTurnTriggers: number; energyDebt: number; attacksThisTurn: number; lastBugEvent: BugEvent | null; popupTurn: number; popupOpen: boolean; popupResolved: boolean; threat: number; log: string[] };
type Run = { screen: Screen; hp: number; maxHp: number; cards: CardTemplate[]; tier: number; completed: string[]; currentNode: string | null; battle: Battle | null; rewardChoices: CardTemplate[]; battlesWon: number; bugsTriggered: number; elitesDefeated: number };

const CARD_LIBRARY: CardTemplate[] = [
  { key: 'strike', name: 'Compile Strike', code: 'compile()', art: '/card-art/compile-strike.webp', cost: 1, kind: 'attack', damage: 6 },
  { key: 'hotfix', name: 'Hotfix', code: 'patch --quick', art: '/card-art/hotfix.webp', cost: 1, kind: 'skill', block: 6 },
  { key: 'duck', name: 'Rubber Duck', code: 'explain(issue)', art: '/card-art/rubber-duck.webp', cost: 1, kind: 'skill', draw: 2 },
  { key: 'refactor', name: 'Refactor', code: 'clean(codebase)', art: '/card-art/refactor.webp', cost: 2, kind: 'attack', damage: 11 },
  { key: 'cache', name: 'Cache Shield', code: 'memoize(defense)', art: '/card-art/cache-shield.webp', cost: 2, kind: 'skill', block: 12 },
  { key: 'trace', name: 'Stack Trace', code: 'trace(stack)', art: '/card-art/stack-trace.webp', cost: 1, kind: 'attack', damage: 4, draw: 1 },
  { key: 'rollback', name: 'Rollback', code: 'git revert pain', art: '/card-art/rollback.webp', cost: 1, kind: 'skill', heal: 5 },
  { key: 'gc', name: 'Garbage Collect', code: 'gc.collect()', art: '/card-art/garbage-collect.webp', cost: 1, kind: 'skill', damage: 4, block: 4 },
  { key: 'pair', name: 'Pair Program', code: 'await teammate()', art: '/card-art/pair-program.webp', cost: 0, kind: 'skill', energy: 1 },
  { key: 'overclock', name: 'Overclock', code: 'cpu++', art: '/card-art/overclock.webp', cost: 2, kind: 'attack', damage: 15, selfDamage: 3 },
  { key: 'test', name: 'Unit Test', code: 'expect(safe)', art: '/card-art/unit-test.webp', cost: 1, kind: 'skill', block: 5, draw: 1 },
  { key: 'ship', name: 'Ship It', code: 'deploy --force', art: '/card-art/ship-it.webp', cost: 3, kind: 'attack', damage: 22 },
];
const byKey = (key: string) => CARD_LIBRARY.find((card) => card.key === key)!;
const STARTER_DECK = ['strike', 'strike', 'strike', 'strike', 'hotfix', 'hotfix', 'hotfix', 'hotfix', 'duck', 'pair'].map(byKey);

const ENEMIES: Record<EnemyKey, Enemy> = {
  folder: { name: 'Corrupted Folder', process: 'folder.exe', icon: '📁', hp: 35, kind: 'battle', feature: '每 3 回合自我备份，获得 Block。' },
  cursor: { name: 'Broken Cursor', process: 'cursor.dll', icon: '↖', hp: 32, kind: 'battle', feature: '每回合第一张 Attack 少造成 3 伤害。' },
  trash: { name: 'Trash Beast', process: 'recycle.bin', icon: '🗑', hp: 44, kind: 'battle', feature: '攻击力随回合缓慢增长。' },
  frozen: { name: 'Frozen Window', process: 'window_404.exe', icon: '❐', hp: 40, kind: 'battle', feature: '每次你触发 Bug，它获得 3 Block。' },
  memoryHog: { name: 'Memory Hog', process: 'memory_hog.exe', icon: '🐗', hp: 62, kind: 'elite', feature: '你每触发 2 次 Bug，它永久获得 +2 攻击力。' },
  antivirus: { name: 'Antivirus', process: 'antivirus.sys', icon: '🛡', hp: 92, kind: 'boss', feature: '每次主动触发 Bug，Threat +1；Threat 越高，扫描越危险。' },
};
const MAP_NODES: MapNode[] = [
  { id: 'folder', tier: 0, kind: 'battle', enemy: 'folder', label: 'Documents', path: 'C:\\Desktop\\Documents' },
  { id: 'cursor', tier: 0, kind: 'battle', enemy: 'cursor', label: 'Pointer Cache', path: 'C:\\Desktop\\System32' },
  { id: 'trash', tier: 1, kind: 'battle', enemy: 'trash', label: 'Recycle Bin', path: 'C:\\Desktop\\$Recycle.Bin' },
  { id: 'frozen', tier: 1, kind: 'battle', enemy: 'frozen', label: 'Frozen App', path: 'C:\\Desktop\\Programs' },
  { id: 'event', tier: 2, kind: 'event', label: 'System Update', path: 'C:\\Desktop\\Updates' },
  { id: 'elite', tier: 2, kind: 'elite', enemy: 'memoryHog', label: 'Memory Hog', path: 'C:\\Desktop\\TaskManager' },
  { id: 'boss', tier: 3, kind: 'boss', enemy: 'antivirus', label: 'Security Center', path: 'C:\\Desktop\\Security' },
];

const shuffle = <T,>(items: T[]) => { const copy = [...items]; for (let i = copy.length - 1; i > 0; i -= 1) { const j = Math.floor(Math.random() * (i + 1)); [copy[i], copy[j]] = [copy[j], copy[i]]; } return copy };
let nextCardId = 1;
const makeCards = (templates: CardTemplate[]) => templates.map((card) => ({ ...card, id: nextCardId++ }));
function drawCards(battle: Battle, count: number) { for (let i = 0; i < count; i += 1) { if (!battle.deck.length) { if (!battle.discard.length) return; battle.deck = shuffle(battle.discard); battle.discard = []; battle.log.unshift('↻ discard.log 已重新载入 deck.memory') } const card = battle.deck.shift(); if (card) battle.hand.push(card) } }
function createBattle(run: Run, enemyKey: EnemyKey): Battle { const cards = shuffle(makeCards(run.cards)); const bugKeys = Object.keys(BUGS) as BugKey[]; const bug = bugKeys[Math.floor(Math.random() * bugKeys.length)]; return { enemyKey, enemyHp: ENEMIES[enemyKey].hp, enemyShield: 0, enemyStrength: 0, playerHp: run.hp, block: 0, energy: 3, turn: 1, deck: cards.slice(5), discard: [], hand: cards.slice(0, 5), bug, bugProgress: 0, bugTriggers: 0, bugTurnTriggers: 0, energyDebt: 0, attacksThisTurn: 0, lastBugEvent: null, popupTurn: 2 + Math.floor(Math.random() * 2), popupOpen: false, popupResolved: false, threat: 0, log: [`ACTIVE BUG: ${BUGS[bug].name}`, `HOST FOUND: ${ENEMIES[enemyKey].name}`] } }
function freshRun(): Run { return { screen: 'map', hp: 48, maxHp: 48, cards: [...STARTER_DECK], tier: 0, completed: [], currentNode: null, battle: null, rewardChoices: [], battlesWon: 0, bugsTriggered: 0, elitesDefeated: 0 } }
function damageEnemy(battle: Battle, amount: number) { const absorbed = Math.min(battle.enemyShield, amount); battle.enemyShield -= absorbed; battle.enemyHp = Math.max(0, battle.enemyHp - amount + absorbed) }
function recordBug(battle: Battle, triggeredBug: BugKey, reward: string, risk: string) { battle.bugTriggers += 1; battle.bugTurnTriggers += 1; battle.log.unshift(`🐛 ${BUGS[triggeredBug].name} #${battle.bugTriggers} // ${reward} // ${risk}`); if (battle.enemyKey === 'frozen') { battle.enemyShield += 3; battle.log.unshift('! Frozen Window 封存 Bug 活动：+3 Block') } if (battle.enemyKey === 'memoryHog' && battle.bugTriggers % 2 === 0) { battle.enemyStrength += 2; battle.log.unshift('! Memory Hog 吞掉调试数据：+2 攻击力') } if (battle.enemyKey === 'antivirus') { battle.threat = Math.min(6, battle.threat + 1); battle.log.unshift(`⚠ ANTIVIRUS THREAT LEVEL ${battle.threat}/6`) } const mutatedTo = nextBugKey(triggeredBug); battle.bug = mutatedTo; battle.bugProgress = 0; battle.lastBugEvent = { triggeredName: BUGS[triggeredBug].name, reward, risk, mutatedTo }; battle.log.unshift(`↻ BUG MUTATED // ${BUGS[triggeredBug].name} → ${BUGS[mutatedTo].name}`) }
function intentFor(battle: Battle) { const strength = battle.enemyStrength; switch (battle.enemyKey) { case 'folder': return battle.turn % 3 === 0 ? { damage: 5 + strength, block: 8, label: '备份 + 攻击' } : { damage: 7 + strength, block: 0, label: '文件投掷' }; case 'cursor': return { damage: (battle.turn % 2 === 0 ? 10 : 6) + strength, block: 0, label: battle.turn % 2 === 0 ? '乱点双击' : '指针突刺' }; case 'trash': return { damage: 6 + Math.floor(battle.turn / 2) * 2 + strength, block: 0, label: '垃圾堆积' }; case 'frozen': return battle.turn % 2 === 0 ? { damage: 5 + strength, block: 7, label: '冻结 + 攻击' } : { damage: 9 + strength, block: 0, label: '未响应' }; case 'memoryHog': return { damage: (battle.turn % 3 === 0 ? 14 : 9) + strength, block: 0, label: battle.turn % 3 === 0 ? '内存峰值' : '内存挪用' }; case 'antivirus': return { damage: (battle.turn % 3 === 0 ? 13 : 8) + strength + battle.threat * 2, block: 0, label: battle.turn % 3 === 0 ? 'FULL SCAN' : 'QUICK SCAN' } } }
const rewardOptions = () => shuffle(CARD_LIBRARY.filter((card) => !['strike', 'hotfix'].includes(card.key))).slice(0, 3);

export default function Page() {
  const [run, setRun] = useState<Run>(freshRun);
  const battle = run.battle;
  const canPlay = useMemo(() => Boolean(battle?.hand.some((card) => card.cost <= battle.energy)), [battle?.hand, battle?.energy]);
  const enterNode = (node: MapNode) => { if (node.tier !== run.tier) return; if (node.kind === 'event') { setRun((previous) => ({ ...previous, screen: 'event', currentNode: node.id })); return } if (node.enemy) setRun((previous) => ({ ...previous, screen: 'battle', currentNode: node.id, battle: createBattle(previous, node.enemy!) })) };
  const playCard = (cardId: number) => setRun((previous) => {
    if (previous.screen !== 'battle' || !previous.battle || previous.battle.popupOpen) return previous;
    const next = structuredClone(previous) as Run; const active = next.battle!; const played = active.hand.find((card) => card.id === cardId); if (!played || played.cost > active.energy) return previous;
    active.hand = active.hand.filter((card) => card.id !== cardId); active.energy -= played.cost; const energyAfterSpend = active.energy;
    let cardDamage = played.damage ?? 0; if (active.enemyKey === 'cursor' && played.kind === 'attack' && active.attacksThisTurn === 0) { cardDamage = Math.max(0, cardDamage - 3); active.log.unshift('! Broken Cursor 让第一次 Attack 偏移：伤害 -3') }
    if (cardDamage) damageEnemy(active, cardDamage); if (played.block) active.block += played.block; if (played.heal) active.playerHp = Math.min(previous.maxHp, active.playerHp + played.heal); if (played.selfDamage) active.playerHp = Math.max(0, active.playerHp - played.selfDamage); if (played.energy) active.energy += played.energy; if (played.draw) drawCards(active, played.draw); active.discard.push(played); if (played.kind === 'attack') active.attacksThisTurn += 1; active.log.unshift(`> ${played.name} // ${describeCard(played)}`);
    const triggeredBug = active.bug; const bugResult = advanceBugProgress(triggeredBug, active.bugProgress, { cardKind: played.kind, cost: played.cost, blockGained: played.block ?? 0, cardsDrawn: played.draw ?? 0, energyAfterSpend }); active.bugProgress = bugResult.progress;
    if (bugResult.triggered) {
      if (triggeredBug === 'overflow') { drawCards(active, 2); active.energy += 1; active.enemyStrength += 1; recordBug(active, triggeredBug, '抽 2，+1 Energy', '敌人 +1 攻击力') }
      else if (triggeredBug === 'memory') { drawCards(active, 2); active.playerHp = Math.max(0, active.playerHp - 2); recordBug(active, triggeredBug, '额外抽 2', '失去 2 HP') }
      else if (triggeredBug === 'hotPath') { damageEnemy(active, 6); active.playerHp = Math.max(0, active.playerHp - 2); recordBug(active, triggeredBug, '额外 6 伤害', '失去 2 HP') }
      else if (triggeredBug === 'firewall') { active.block += 8; active.energyDebt += 1; recordBug(active, triggeredBug, '+8 Block', '下回合 -1 Energy') }
      else { active.energy += 2; active.playerHp = Math.max(0, active.playerHp - 3); recordBug(active, triggeredBug, '+2 Energy', '失去 3 HP') }
    }
    if (active.playerHp <= 0) { next.hp = 0; next.battle = null; next.screen = 'defeat' }
    else if (active.enemyHp <= 0) { next.hp = active.playerHp; next.bugsTriggered += active.bugTriggers; next.battlesWon += 1; next.completed.push(next.currentNode!); if (ENEMIES[active.enemyKey].kind === 'elite') next.elitesDefeated += 1; next.battle = null; if (active.enemyKey === 'antivirus') next.screen = 'victory'; else { next.screen = 'reward'; next.rewardChoices = rewardOptions() } }
    return next;
  });
  const endTurn = () => setRun((previous) => {
    if (previous.screen !== 'battle' || !previous.battle || previous.battle.popupOpen) return previous;
    const next = structuredClone(previous) as Run; const active = next.battle!; const intent = intentFor(active); const damageTaken = Math.max(0, intent.damage - active.block); active.playerHp = Math.max(0, active.playerHp - damageTaken); active.log.unshift(`! ${ENEMIES[active.enemyKey].name} // ${intent.label} ${intent.damage} // HP -${damageTaken}`); if (active.playerHp <= 0) { next.hp = 0; next.battle = null; next.screen = 'defeat'; return next }
    active.enemyShield = intent.block; active.discard.push(...active.hand); active.hand = []; active.block = 0; active.turn += 1; active.energy = Math.max(0, 3 - active.energyDebt); if (active.energyDebt) active.log.unshift(`⚠ ENERGY DEBT // 本回合 -${active.energyDebt} Energy`); active.energyDebt = 0; active.attacksThisTurn = 0; active.bugProgress = 0; active.bugTurnTriggers = 0; active.lastBugEvent = null; drawCards(active, 5); if (!active.popupResolved && active.turn === active.popupTurn) active.popupOpen = true; active.log.unshift(`— TURN ${active.turn} // Energy restored`); return next;
  });
  const resolvePopup = (choice: 'allow' | 'deny') => setRun((previous) => { if (!previous.battle?.popupOpen) return previous; const next = structuredClone(previous) as Run; const active = next.battle!; if (choice === 'allow') { drawCards(active, 2); active.energy += 1; active.playerHp = Math.max(0, active.playerHp - 4); active.log.unshift('▣ POP-UP // ALLOW：抽 2，+1 Energy，失去 4 HP') } else { active.block += 9; active.energyDebt += 1; active.log.unshift('▣ POP-UP // NOT NOW：+9 Block，下回合 -1 Energy') } active.popupOpen = false; active.popupResolved = true; if (active.playerHp <= 0) { next.hp = 0; next.battle = null; next.screen = 'defeat' } return next });
  const finishReward = (card?: CardTemplate) => setRun((previous) => ({ ...previous, cards: card ? [...previous.cards, card] : previous.cards, tier: previous.tier + 1, screen: 'map', battle: null, currentNode: null, rewardChoices: [] }));
  const resolveEvent = (choice: 'repair' | 'optimize') => setRun((previous) => ({ ...previous, hp: choice === 'repair' ? Math.min(previous.maxHp, previous.hp + 14) : previous.hp, cards: choice === 'optimize' ? [...previous.cards, byKey('test')] : previous.cards, completed: [...previous.completed, previous.currentNode!], tier: previous.tier + 1, screen: 'map', currentNode: null }));
  const bugInfo = battle ? BUGS[battle.bug] : null; const enemy = battle ? ENEMIES[battle.enemyKey] : null; const intent = battle ? intentFor(battle) : null; const displayedHp = run.screen === 'battle' && battle ? battle.playerHp : run.hp;
  return <main><header className="topbar"><div className="brand"><span className="brand-mark">B_</span><div><h1>BUGBOUND</h1><p>desktop run // act 1 vertical slice</p></div></div><div className="run-health"><span>SYSTEM HEALTH</span><strong>{displayedHp}/{run.maxHp}</strong></div><button className="ghost-button" onClick={() => setRun(freshRun())}>↻ NEW RUN</button></header>
    {run.screen === 'map' ? <MapScreen run={run} onEnter={enterNode} /> : null}
    {run.screen === 'battle' && battle && bugInfo && enemy && intent ? <BattleScreen run={run} battle={battle} bug={bugInfo} enemy={enemy} intent={intent} canPlay={canPlay} onPlay={playCard} onEndTurn={endTurn} onPopup={resolvePopup} /> : null}
    {run.screen === 'reward' ? <RewardScreen choices={run.rewardChoices} onChoose={finishReward} /> : null}
    {run.screen === 'event' ? <EventScreen run={run} onChoose={resolveEvent} /> : null}
    {run.screen === 'victory' || run.screen === 'defeat' ? <RunResult run={run} onReset={() => setRun(freshRun())} /> : null}
  </main>;
}

function MapScreen({ run, onEnter }: { run: Run; onEnter: (node: MapNode) => void }) { return <section className="map-shell"><div className="explorer-bar"><span className="window-controls"><i /><i /><i /></span><strong>File Explorer</strong><code>C:\Desktop\Act_1</code></div><div className="map-intro"><div><span>ACT 1 / DESKTOP</span><h2>Choose a system path.</h2><p>每场战斗只加载一个 Bug Monitor；每次触发后它会立即 Mutation，离开战斗后清除。</p></div><div className="developer-id"><span>🧑‍💻</span><div><small>USER PROFILE</small><strong>Developer</strong><p>只是一个被吸进电脑的普通开发者。</p></div></div></div><div className="path-map">{[0, 1, 2, 3].map((tier) => <div className="map-tier" key={tier}><span className="tier-label">{tier === 3 ? 'ROOT ACCESS' : `PATH 0${tier + 1}`}</span><div className="tier-nodes">{MAP_NODES.filter((node) => node.tier === tier).map((node) => { const unlocked = run.tier === tier; const completed = run.completed.includes(node.id); const passed = run.tier > tier && !completed; return <button key={node.id} className={`map-node ${node.kind} ${unlocked ? 'unlocked' : ''} ${completed ? 'completed' : ''}`} disabled={!unlocked} onClick={() => onEnter(node)}><span className="node-icon">{node.kind === 'battle' ? '⚔' : node.kind === 'elite' ? '☠' : node.kind === 'event' ? '▣' : '🛡'}</span><span><small>{node.kind.toUpperCase()}</small><strong>{node.label}</strong><code>{node.path}</code></span><b>{completed ? '✓' : passed ? '—' : unlocked ? 'OPEN' : '🔒'}</b></button> })}</div></div>)}</div><footer className="run-footer"><span>DECK {run.cards.length}</span><span>BATTLES {run.battlesWon}</span><span>BUG TRIGGERS {run.bugsTriggered}</span></footer></section> }

function BattleScreen({ run, battle, bug, enemy, intent, canPlay, onPlay, onEndTurn, onPopup }: { run: Run; battle: Battle; bug: Bug; enemy: Enemy; intent: ReturnType<typeof intentFor>; canPlay: boolean; onPlay: (id: number) => void; onEndTurn: () => void; onPopup: (choice: 'allow' | 'deny') => void }) { return <><section className="mission-line"><span>{enemy.kind === 'boss' ? 'SECURITY ALERT' : 'ACTIVE PROCESS'}</span><p>{enemy.feature}</p><span className="turn">TURN {String(battle.turn).padStart(2, '0')}</span></section><div className="workspace"><section className="battle-panel">{battle.enemyKey === 'antivirus' ? <ThreatMeter threat={battle.threat} /> : null}<div className="combatants"><div className="actor player"><div className="avatar developer-avatar">🧑‍💻</div><div className="actor-copy"><div className="eyebrow">PLAYER_PROCESS</div><h2>Developer</h2><StatBar label="HP" value={battle.playerHp} max={run.maxHp} tone="green" /><div className="mini-stats"><span>🛡 {battle.block} BLOCK</span><span>⚡ {battle.energy}/3 ENERGY</span></div>{battle.energyDebt ? <div className="energy-debt">NEXT TURN −{battle.energyDebt} ENERGY</div> : null}</div></div><div className="versus">VS</div><div className="actor enemy"><div className="actor-copy"><div className="eyebrow danger">{enemy.process}</div><h2>{enemy.name}</h2><StatBar label="HP" value={battle.enemyHp} max={enemy.hp} tone="red" />{battle.enemyShield ? <div className="enemy-shield">🛡 {battle.enemyShield} BLOCK</div> : null}<div className="intent"><span>{intent.label}</span><strong>⚔ {intent.damage} DAMAGE{intent.block ? ` + ${intent.block} BLOCK` : ''}</strong></div>{battle.enemyStrength ? <div className="enemy-mods"><span>+{battle.enemyStrength} STR</span></div> : null}</div><div className={`avatar enemy-avatar ${battle.enemyKey}`}>{enemy.icon}</div></div></div><div className="hand-zone"><div className="zone-heading"><div><span>HAND</span><small>{battle.hand.length} cards · deck {battle.deck.length} · discard {battle.discard.length}</small></div><button className="end-button" onClick={onEndTurn}>END TURN <b>↵</b></button></div><div className="cards">{battle.hand.map((card, index) => <CardButton key={card.id} card={card} index={index} disabled={card.cost > battle.energy} onPlay={onPlay} />)}{!battle.hand.length ? <div className="empty-hand">HAND EMPTY</div> : null}</div>{!canPlay ? <p className="hint">没有可出的牌了——结束回合，让系统继续运行。</p> : null}</div></section><aside className="sidebar"><BugMonitor bug={bug} battle={battle} /><section className="terminal window-panel"><WindowTitle title="Runtime.log" /><div className="log-lines">{battle.log.slice(0, 10).map((line, index) => <p key={`${line}-${index}`} className={line.includes('BUG') || line.includes('🐛') || line.includes('THREAT') ? 'alert' : ''}>{line}</p>)}</div></section></aside></div>{battle.popupOpen ? <PopupDialog onChoose={onPopup} /> : null}</> }

function CardButton({ card, index, disabled, onPlay }: { card: Card; index: number; disabled: boolean; onPlay: (id: number) => void }) { return <button className={`card drawn-card ${card.kind}`} style={{ '--draw-order': index } as CSSProperties} disabled={disabled} onClick={() => onPlay(card.id)}><span className="cost">{card.cost}</span><span className="kind">{card.kind.toUpperCase()}</span><span className="card-art"><img src={card.art} alt="" /></span><strong>{card.name}</strong><code>{card.code}</code><span className="effect">{describeCard(card)}</span><span className="run">{disabled ? 'INSUFFICIENT ENERGY' : 'CLICK TO RUN'}</span></button> }
function BugMonitor({ bug, battle }: { bug: Bug; battle: Battle }) { const event = battle.lastBugEvent; return <section className={`bug-monitor window-panel ${event ? 'triggered' : ''}`}><WindowTitle title="BugMonitor.exe" live /><div className="bug-head"><div className="bug-symbol">{bug.icon}</div><div><span>{bug.code} / {bug.category}</span><h3>{bug.name}</h3></div></div><div className="bug-rule trigger"><span>TRIGGER</span><p>{bug.trigger}</p></div>{bug.target ? <div className="bug-progress"><span>{bug.progressLabel}</span><div><i style={{ width: `${Math.min(100, (battle.bugProgress / bug.target) * 100)}%` }} /></div><strong>{battle.bugProgress}/{bug.target}</strong></div> : null}<div className="bug-rule reward"><span>REWARD</span><p>{bug.reward}</p></div><div className="bug-rule risk"><span>RISK</span><p>{bug.risk}</p></div><div className="trigger-count"><div><span>THIS TURN</span><strong>{battle.bugTurnTriggers}</strong></div><div><span>THIS BATTLE</span><strong>{battle.bugTriggers}</strong></div></div>{event ? <div key={battle.bugTriggers} className="bug-feedback"><strong>BUG MUTATED</strong><span>{event.triggeredName} → {BUGS[event.mutatedTo].name}</span><small>TRIGGERED #{battle.bugTriggers} // + {event.reward} / − {event.risk}</small></div> : null}<p className="bug-note">每次触发后立即换成新目标；同回合可继续触发。Bug 效果不会触发下一个 Bug。</p></section> }
function WindowTitle({ title, live = false }: { title: string; live?: boolean }) { return <div className="window-title"><span>{title}</span><span className="window-actions"><i className={live ? 'live' : ''} />─ □ ×</span></div> }
function ThreatMeter({ threat }: { threat: number }) { return <div className={`threat-meter threat-${threat}`}><span>🛡 ANTIVIRUS THREAT LEVEL</span><div>{Array.from({ length: 6 }, (_, index) => <i key={index} className={index < threat ? 'filled' : ''} />)}</div><strong>{threat}/6</strong><small>每次 Bug Trigger 使扫描伤害 +2</small></div> }
function PopupDialog({ onChoose }: { onChoose: (choice: 'allow' | 'deny') => void }) { return <div className="overlay popup-overlay" role="dialog" aria-modal="true"><div className="os-dialog"><WindowTitle title="Unknown process permission" /><div className="dialog-body"><div className="dialog-icon">!</div><div><h2>Allow background optimization?</h2><p><code>helper_undefined.exe</code> 想在本回合优化你的资源。两个选择都有代价。</p></div></div><div className="dialog-choices"><button onClick={() => onChoose('allow')}><strong>ALLOW</strong><span>抽 2，+1 Energy</span><small>Risk：失去 4 HP</small></button><button onClick={() => onChoose('deny')}><strong>NOT NOW</strong><span>+9 Block</span><small>Risk：下回合 -1 Energy</small></button></div></div></div> }
function RewardScreen({ choices, onChoose }: { choices: CardTemplate[]; onChoose: (card?: CardTemplate) => void }) { return <section className="center-screen"><div className="reward-window"><WindowTitle title="Package Manager / Battle reward" /><div className="screen-copy"><span>PROCESS TERMINATED</span><h2>Install one new command.</h2><p>牌会保留到这次 Run 结束。</p></div><div className="reward-cards">{choices.map((card) => <button key={card.key} className={`card ${card.kind}`} onClick={() => onChoose(card)}><span className="cost">{card.cost}</span><span className="kind">{card.kind.toUpperCase()}</span><span className="card-art"><img src={card.art} alt="" /></span><strong>{card.name}</strong><code>{card.code}</code><span className="effect">{describeCard(card)}</span><span className="run">INSTALL</span></button>)}</div><button className="skip-button" onClick={() => onChoose()}>跳过安装 →</button></div></section> }
function EventScreen({ run, onChoose }: { run: Run; onChoose: (choice: 'repair' | 'optimize') => void }) { return <section className="center-screen"><div className="event-window"><WindowTitle title="Windows Update" /><div className="update-visual"><span>↻</span><i style={{ width: '73%' }} /></div><div className="screen-copy"><span>OPTIONAL UPDATE FOUND</span><h2>One maintenance window is available.</h2><p>没有免费升级：修复现有系统，或为后续战斗安装新工具。</p></div><div className="event-options"><button onClick={() => onChoose('repair')}><span>SYSTEM RESTORE</span><strong>恢复 14 HP</strong><small>当前 {run.hp}/{run.maxHp}</small></button><button onClick={() => onChoose('optimize')}><span>FEATURE UPDATE</span><strong>获得 Unit Test</strong><small>5 Block · 抽 1</small></button></div></div></section> }
function RunResult({ run, onReset }: { run: Run; onReset: () => void }) { const won = run.screen === 'victory'; return <section className="center-screen"><div className={`result ${won ? 'won' : 'lost'}`}><span>{won ? 'ACT 1 COMPLETE' : 'FATAL ERROR'}</span><div className="result-icon">{won ? '💻' : '⊘'}</div><h2>{won ? 'Antivirus 已撤销隔离。' : '进程已崩溃。'}</h2><p>{won ? '你证明了自己不是 malware——至少暂时如此。' : 'Desktop 仍在等下一个 Developer。'}</p><div className="run-summary"><span><small>BATTLES</small>{run.battlesWon}</span><span><small>BUG TRIGGERS</small>{run.bugsTriggered}</span><span><small>FINAL DECK</small>{run.cards.length}</span></div><button onClick={onReset}>START NEW RUN ↻</button></div></section> }
function StatBar({ label, value, max, tone }: { label: string; value: number; max: number; tone: string }) { return <div className="stat-wrap"><div className="stat-label"><span>{label}</span><strong>{value}/{max}</strong></div><div className={`stat-bar ${tone}`}><i style={{ width: `${Math.max(0, value / max) * 100}%` }} /></div></div> }
function describeCard(card: CardTemplate) { const parts = []; if (card.damage) parts.push(`造成 ${card.damage} 伤害`); if (card.block) parts.push(`获得 ${card.block} Block`); if (card.heal) parts.push(`修复 ${card.heal} HP`); if (card.draw) parts.push(`抽 ${card.draw} 张牌`); if (card.energy) parts.push(`获得 ${card.energy} Energy`); if (card.selfDamage) parts.push(`失去 ${card.selfDamage} HP`); return parts.join(' · ') }
